
/**
 *
 * @author KENZIE
 */
public class Procal extends javax.swing.JFrame {

    
    /**
     * Creates new form Procal
     */
    
    double firstnum, secondnum, ans;
    int calculate, calculate1;
    int value1, value2, value3, value4;
    String operation;
    
    
    public Procal() {
        initComponents();
    }

    public void arithmetic_OP(){
        switch (calculate){
            case 1:
                ans= firstnum + Double.parseDouble(TextInput.getText());
                TextInput.setText(Double.toString(ans));
                break;
            case 2:
                ans= firstnum - Double.parseDouble(TextInput.getText());
                TextInput.setText(Double.toString(ans));
                break;
            case 3:
                ans= firstnum * Double.parseDouble(TextInput.getText());
                TextInput.setText(Double.toString(ans));
                break;
            case 4:
                ans= firstnum / Double.parseDouble(TextInput.getText());
                TextInput.setText(Double.toString(ans));
                break;    
        }
    }
    
    public void relational_OP(){
        if (operation == ">"){        
                TextInput.setText(String.valueOf(firstnum > secondnum));
        }
        else if (operation == ">="){       
                TextInput.setText(String.valueOf(firstnum >= secondnum));
        }
        else if (operation == "<"){
                TextInput.setText(String.valueOf(firstnum < secondnum));        
        }
        else if (operation == "<="){
                TextInput.setText(String.valueOf(firstnum <= secondnum));
        }
        else if (operation == "!="){
                TextInput.setText(String.valueOf(firstnum != secondnum));
        }
        else if (operation == "=="){
                TextInput.setText(String.valueOf(firstnum == secondnum));
        }
        
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TextInput = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        AllClearButton = new javax.swing.JButton();
        NotEqualButton = new javax.swing.JButton();
        MultiplicationButton = new javax.swing.JButton();
        EqualsButton = new javax.swing.JButton();
        Parenthesis = new javax.swing.JButton();
        EightButton = new javax.swing.JButton();
        SevenButton = new javax.swing.JButton();
        LTButton = new javax.swing.JButton();
        NineButton = new javax.swing.JButton();
        ANDButton = new javax.swing.JButton();
        DivideButton = new javax.swing.JButton();
        ORButton = new javax.swing.JButton();
        AdditionButton = new javax.swing.JButton();
        FiveButton = new javax.swing.JButton();
        FourButton = new javax.swing.JButton();
        LTEQButton = new javax.swing.JButton();
        SixButton = new javax.swing.JButton();
        BitwiseButton = new javax.swing.JButton();
        SubtrationButton = new javax.swing.JButton();
        TwoButton = new javax.swing.JButton();
        OneButton = new javax.swing.JButton();
        GTButton = new javax.swing.JButton();
        ThreeButton = new javax.swing.JButton();
        NotButton = new javax.swing.JButton();
        EqualButton = new javax.swing.JButton();
        ZeroButton = new javax.swing.JButton();
        DeciButton = new javax.swing.JButton();
        GTEQButton = new javax.swing.JButton();
        ModulusButton = new javax.swing.JButton();
        Stored = new javax.swing.JLabel();

        jButton13.setText("jButton1");
        jButton13.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton13.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton13.setPreferredSize(new java.awt.Dimension(29, 25));

        jButton14.setText("jButton1");
        jButton14.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton14.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton14.setPreferredSize(new java.awt.Dimension(29, 25));

        jButton15.setText("jButton1");
        jButton15.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton15.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton15.setPreferredSize(new java.awt.Dimension(29, 25));

        jButton16.setText("jButton1");
        jButton16.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton16.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton16.setPreferredSize(new java.awt.Dimension(29, 25));

        jButton17.setText("jButton1");
        jButton17.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton17.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton17.setPreferredSize(new java.awt.Dimension(29, 25));

        jButton18.setText("jButton1");
        jButton18.setMaximumSize(new java.awt.Dimension(29, 25));
        jButton18.setMinimumSize(new java.awt.Dimension(29, 25));
        jButton18.setPreferredSize(new java.awt.Dimension(29, 25));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        TextInput.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TextInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 4, true));

        DeleteButton.setBackground(new java.awt.Color(102, 0, 0));
        DeleteButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("DEL");
        DeleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        DeleteButton.setMaximumSize(new java.awt.Dimension(29, 25));
        DeleteButton.setMinimumSize(new java.awt.Dimension(29, 25));
        DeleteButton.setPreferredSize(new java.awt.Dimension(29, 25));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteInput(evt);
            }
        });

        AllClearButton.setBackground(new java.awt.Color(102, 0, 0));
        AllClearButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        AllClearButton.setForeground(new java.awt.Color(255, 255, 255));
        AllClearButton.setText("AC");
        AllClearButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 3, true));
        AllClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllClear(evt);
            }
        });

        NotEqualButton.setBackground(new java.awt.Color(255, 51, 0));
        NotEqualButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        NotEqualButton.setForeground(new java.awt.Color(255, 255, 255));
        NotEqualButton.setText("!=");
        NotEqualButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));

        MultiplicationButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        MultiplicationButton.setText("*");
        MultiplicationButton.setMaximumSize(new java.awt.Dimension(29, 25));
        MultiplicationButton.setMinimumSize(new java.awt.Dimension(29, 25));
        MultiplicationButton.setPreferredSize(new java.awt.Dimension(29, 25));
        MultiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicationButtonActionPerformed(evt);
            }
        });

        EqualsButton.setBackground(new java.awt.Color(255, 51, 0));
        EqualsButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        EqualsButton.setForeground(new java.awt.Color(255, 255, 255));
        EqualsButton.setText("==");
        EqualsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));

        Parenthesis.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        Parenthesis.setText("()");
        Parenthesis.setMaximumSize(new java.awt.Dimension(29, 25));
        Parenthesis.setMinimumSize(new java.awt.Dimension(29, 25));
        Parenthesis.setPreferredSize(new java.awt.Dimension(29, 25));
        Parenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParthesisAction(evt);
            }
        });

        EightButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        EightButton.setText("8");
        EightButton.setMaximumSize(new java.awt.Dimension(29, 25));
        EightButton.setMinimumSize(new java.awt.Dimension(29, 25));
        EightButton.setPreferredSize(new java.awt.Dimension(29, 25));
        EightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightButtonActionPerformed(evt);
            }
        });

        SevenButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        SevenButton.setText("7");
        SevenButton.setMaximumSize(new java.awt.Dimension(29, 25));
        SevenButton.setMinimumSize(new java.awt.Dimension(29, 25));
        SevenButton.setPreferredSize(new java.awt.Dimension(29, 25));
        SevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenButtonActionPerformed(evt);
            }
        });

        LTButton.setBackground(new java.awt.Color(255, 51, 0));
        LTButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        LTButton.setForeground(new java.awt.Color(255, 255, 255));
        LTButton.setText("<");
        LTButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        LTButton.setMaximumSize(new java.awt.Dimension(29, 25));
        LTButton.setMinimumSize(new java.awt.Dimension(29, 25));
        LTButton.setPreferredSize(new java.awt.Dimension(29, 25));
        LTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LTButtonActionPerformed(evt);
            }
        });

        NineButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        NineButton.setText("9");
        NineButton.setMaximumSize(new java.awt.Dimension(29, 25));
        NineButton.setMinimumSize(new java.awt.Dimension(29, 25));
        NineButton.setPreferredSize(new java.awt.Dimension(29, 25));
        NineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineButtonActionPerformed(evt);
            }
        });

        ANDButton.setBackground(new java.awt.Color(204, 0, 153));
        ANDButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ANDButton.setForeground(new java.awt.Color(255, 255, 255));
        ANDButton.setText("&&");
        ANDButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));

        DivideButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        DivideButton.setText("/");
        DivideButton.setMaximumSize(new java.awt.Dimension(29, 25));
        DivideButton.setMinimumSize(new java.awt.Dimension(29, 25));
        DivideButton.setPreferredSize(new java.awt.Dimension(29, 25));
        DivideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideButtonActionPerformed(evt);
            }
        });

        ORButton.setBackground(new java.awt.Color(204, 0, 153));
        ORButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ORButton.setForeground(new java.awt.Color(255, 255, 255));
        ORButton.setText("||");
        ORButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));

        AdditionButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        AdditionButton.setText("+");
        AdditionButton.setMaximumSize(new java.awt.Dimension(29, 25));
        AdditionButton.setMinimumSize(new java.awt.Dimension(29, 25));
        AdditionButton.setPreferredSize(new java.awt.Dimension(29, 25));
        AdditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionButtonActionPerformed(evt);
            }
        });

        FiveButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        FiveButton.setText("5");
        FiveButton.setMaximumSize(new java.awt.Dimension(29, 25));
        FiveButton.setMinimumSize(new java.awt.Dimension(29, 25));
        FiveButton.setPreferredSize(new java.awt.Dimension(29, 25));
        FiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveButtonActionPerformed(evt);
            }
        });

        FourButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        FourButton.setText("4");
        FourButton.setMaximumSize(new java.awt.Dimension(29, 25));
        FourButton.setMinimumSize(new java.awt.Dimension(29, 25));
        FourButton.setPreferredSize(new java.awt.Dimension(29, 25));
        FourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourButtonActionPerformed(evt);
            }
        });

        LTEQButton.setBackground(new java.awt.Color(255, 51, 0));
        LTEQButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        LTEQButton.setForeground(new java.awt.Color(255, 255, 255));
        LTEQButton.setText("<=");
        LTEQButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        LTEQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LTEQButtonActionPerformed(evt);
            }
        });

        SixButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        SixButton.setText("6");
        SixButton.setMaximumSize(new java.awt.Dimension(29, 25));
        SixButton.setMinimumSize(new java.awt.Dimension(29, 25));
        SixButton.setPreferredSize(new java.awt.Dimension(29, 25));
        SixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixButtonActionPerformed(evt);
            }
        });

        BitwiseButton.setBackground(new java.awt.Color(204, 0, 153));
        BitwiseButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        BitwiseButton.setForeground(new java.awt.Color(255, 255, 255));
        BitwiseButton.setText("^");
        BitwiseButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));
        BitwiseButton.setMaximumSize(new java.awt.Dimension(29, 25));
        BitwiseButton.setMinimumSize(new java.awt.Dimension(29, 25));
        BitwiseButton.setPreferredSize(new java.awt.Dimension(29, 25));

        SubtrationButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        SubtrationButton.setText("-");
        SubtrationButton.setMaximumSize(new java.awt.Dimension(29, 25));
        SubtrationButton.setMinimumSize(new java.awt.Dimension(29, 25));
        SubtrationButton.setPreferredSize(new java.awt.Dimension(29, 25));
        SubtrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtrationButtonActionPerformed(evt);
            }
        });

        TwoButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        TwoButton.setText("2");
        TwoButton.setMaximumSize(new java.awt.Dimension(29, 25));
        TwoButton.setMinimumSize(new java.awt.Dimension(29, 25));
        TwoButton.setPreferredSize(new java.awt.Dimension(29, 25));
        TwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoButtonActionPerformed(evt);
            }
        });

        OneButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        OneButton.setText("1");
        OneButton.setMaximumSize(new java.awt.Dimension(29, 25));
        OneButton.setMinimumSize(new java.awt.Dimension(29, 25));
        OneButton.setPreferredSize(new java.awt.Dimension(29, 25));
        OneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneButtonActionPerformed(evt);
            }
        });

        GTButton.setBackground(new java.awt.Color(255, 51, 0));
        GTButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        GTButton.setForeground(new java.awt.Color(255, 255, 255));
        GTButton.setText(">");
        GTButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        GTButton.setMaximumSize(new java.awt.Dimension(29, 25));
        GTButton.setMinimumSize(new java.awt.Dimension(29, 25));
        GTButton.setPreferredSize(new java.awt.Dimension(29, 25));
        GTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GTButtonActionPerformed(evt);
            }
        });

        ThreeButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ThreeButton.setText("3");
        ThreeButton.setMaximumSize(new java.awt.Dimension(29, 25));
        ThreeButton.setMinimumSize(new java.awt.Dimension(29, 25));
        ThreeButton.setPreferredSize(new java.awt.Dimension(29, 25));
        ThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeButtonActionPerformed(evt);
            }
        });

        NotButton.setBackground(new java.awt.Color(204, 0, 153));
        NotButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        NotButton.setForeground(new java.awt.Color(255, 255, 255));
        NotButton.setText("!");
        NotButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 3, true));
        NotButton.setMaximumSize(new java.awt.Dimension(29, 25));
        NotButton.setMinimumSize(new java.awt.Dimension(29, 25));
        NotButton.setPreferredSize(new java.awt.Dimension(29, 25));

        EqualButton.setBackground(new java.awt.Color(0, 0, 102));
        EqualButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        EqualButton.setForeground(new java.awt.Color(255, 255, 255));
        EqualButton.setText("=");
        EqualButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true));
        EqualButton.setMaximumSize(new java.awt.Dimension(29, 25));
        EqualButton.setMinimumSize(new java.awt.Dimension(29, 25));
        EqualButton.setPreferredSize(new java.awt.Dimension(29, 25));
        EqualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualButtonActionPerformed(evt);
            }
        });

        ZeroButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ZeroButton.setText("0");
        ZeroButton.setMaximumSize(new java.awt.Dimension(29, 25));
        ZeroButton.setMinimumSize(new java.awt.Dimension(29, 25));
        ZeroButton.setPreferredSize(new java.awt.Dimension(29, 25));
        ZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroButtonActionPerformed(evt);
            }
        });

        DeciButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        DeciButton.setText(".");
        DeciButton.setMaximumSize(new java.awt.Dimension(29, 25));
        DeciButton.setMinimumSize(new java.awt.Dimension(29, 25));
        DeciButton.setPreferredSize(new java.awt.Dimension(29, 25));
        DeciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeciButtonActionPerformed(evt);
            }
        });

        GTEQButton.setBackground(new java.awt.Color(255, 51, 0));
        GTEQButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        GTEQButton.setForeground(new java.awt.Color(255, 255, 255));
        GTEQButton.setText(">=");
        GTEQButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 3, true));
        GTEQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GTEQButtonActionPerformed(evt);
            }
        });

        ModulusButton.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ModulusButton.setText("%");
        ModulusButton.setMaximumSize(new java.awt.Dimension(29, 25));
        ModulusButton.setMinimumSize(new java.awt.Dimension(29, 25));
        ModulusButton.setPreferredSize(new java.awt.Dimension(29, 25));
        ModulusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModulusButtonActionPerformed(evt);
            }
        });

        Stored.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Stored.setForeground(new java.awt.Color(255, 0, 0));
        Stored.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AllClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MultiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NotEqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Parenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ANDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LTEQButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ORButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BitwiseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubtrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DeciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModulusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GTEQButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Stored, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Stored, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AllClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotEqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultiplicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parenthesis, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANDButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LTEQButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ORButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdditionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BitwiseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubtrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GTEQButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModulusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private boolean isParenthesisEqual(String text){
        int balanceFactor = 0;
        for(int i = 0; i<text.length(); i++){
            if(text.charAt(i) == '(')
                balanceFactor++;
            if(text.charAt(i) == ')')
                balanceFactor--;
        }
        return balanceFactor == 0;
    }
    private void ParthesisAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParthesisAction
       String textInputText = TextInput.getText();
       if(textInputText.isEmpty()){
           TextInput.setText("(");
           return;
       }
       Boolean isParenEqual = isParenthesisEqual(textInputText);
       String prtlogic = TextInput.getText().substring(TextInput.getText().length()-1);
       if(isParenEqual){
           TextInput.setText(TextInput.getText() + "*(");
       } else if(prtlogic.matches("[0-9]") && !isParenEqual){
           TextInput.setText(TextInput.getText() + ")");
       } else if(prtlogic.matches("[^0-9\\)]") && !isParenEqual){
            TextInput.setText(TextInput.getText() + "(");
       } else {
            TextInput.setText(TextInput.getText() + ")");

       }
    }//GEN-LAST:event_ParthesisAction

    private void AllClear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllClear
        TextInput.setText("");
    }//GEN-LAST:event_AllClear

    private void DeleteInput(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteInput
        int length = TextInput.getText().length();
        int number = TextInput.getText().length() - 1;
        String store;
        
        if(length > 0){
            StringBuilder back = new StringBuilder(TextInput.getText());
            back.deleteCharAt(number);
            store = back.toString();
            TextInput.setText(store);
        }
    }//GEN-LAST:event_DeleteInput

    private void OneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneButtonActionPerformed
        TextInput.setText(TextInput.getText() + "1");
    }//GEN-LAST:event_OneButtonActionPerformed

    private void TwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoButtonActionPerformed
        TextInput.setText(TextInput.getText() + "2");
    }//GEN-LAST:event_TwoButtonActionPerformed

    private void ThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeButtonActionPerformed
        TextInput.setText(TextInput.getText() + "3");
    }//GEN-LAST:event_ThreeButtonActionPerformed

    private void FourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourButtonActionPerformed
        TextInput.setText(TextInput.getText() + "4");
    }//GEN-LAST:event_FourButtonActionPerformed

    private void FiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveButtonActionPerformed
        TextInput.setText(TextInput.getText() + "5");
    }//GEN-LAST:event_FiveButtonActionPerformed

    private void SixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixButtonActionPerformed
        TextInput.setText(TextInput.getText() + "6");
    }//GEN-LAST:event_SixButtonActionPerformed

    private void SevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenButtonActionPerformed
        TextInput.setText(TextInput.getText() + "7");
    }//GEN-LAST:event_SevenButtonActionPerformed

    private void EightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightButtonActionPerformed
        TextInput.setText(TextInput.getText() + "8");
    }//GEN-LAST:event_EightButtonActionPerformed

    private void NineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineButtonActionPerformed
        TextInput.setText(TextInput.getText() + "9");
    }//GEN-LAST:event_NineButtonActionPerformed

    private void ZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroButtonActionPerformed
        TextInput.setText(TextInput.getText() + "0");
    }//GEN-LAST:event_ZeroButtonActionPerformed

    private void DeciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeciButtonActionPerformed
        TextInput.setText(TextInput.getText() + ".");
    }//GEN-LAST:event_DeciButtonActionPerformed

    private void ModulusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModulusButtonActionPerformed
        TextInput.setText(TextInput.getText() + "%");
    }//GEN-LAST:event_ModulusButtonActionPerformed

    private void MultiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicationButtonActionPerformed
        firstnum = Double.parseDouble(TextInput.getText());
        calculate =3;
        TextInput.setText("");
        Stored.setText(firstnum + "*");
    }//GEN-LAST:event_MultiplicationButtonActionPerformed

    private void DivideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideButtonActionPerformed
        firstnum = Double.parseDouble(TextInput.getText());
        calculate =4;
        TextInput.setText("");
        Stored.setText(firstnum + "/");
    }//GEN-LAST:event_DivideButtonActionPerformed

    private void AdditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionButtonActionPerformed
        firstnum = Double.parseDouble(TextInput.getText());
        calculate =1;
        TextInput.setText("");
        Stored.setText(firstnum + "+");
    }//GEN-LAST:event_AdditionButtonActionPerformed

    private void SubtrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtrationButtonActionPerformed
        firstnum = Double.parseDouble(TextInput.getText());
        calculate =2;
        TextInput.setText("");
        Stored.setText(firstnum + "-");
    }//GEN-LAST:event_SubtrationButtonActionPerformed

    private void EqualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualButtonActionPerformed
       arithmetic_OP();
       relational_OP();
       Stored.setText("");
    }//GEN-LAST:event_EqualButtonActionPerformed

    private void LTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LTButtonActionPerformed
        firstnum = Double.parseDouble(TextInput.getText());
        TextInput.setText(" ");
        operation = "<";
    }//GEN-LAST:event_LTButtonActionPerformed

    private void GTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GTButtonActionPerformed
        firstnum = Double.parseDouble(TextInput.getText());
        TextInput.setText(" ");
        operation = ">";
    }//GEN-LAST:event_GTButtonActionPerformed

    private void GTEQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GTEQButtonActionPerformed
        firstnum = Double.parseDouble(TextInput.getText());
        TextInput.setText(" ");
        operation = ">=";
    }//GEN-LAST:event_GTEQButtonActionPerformed

    private void LTEQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LTEQButtonActionPerformed
        firstnum = Double.parseDouble(TextInput.getText());
        TextInput.setText(" ");
        operation = "<=";
    }//GEN-LAST:event_LTEQButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Procal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Procal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Procal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Procal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Procal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANDButton;
    private javax.swing.JButton AdditionButton;
    private javax.swing.JButton AllClearButton;
    private javax.swing.JButton BitwiseButton;
    private javax.swing.JButton DeciButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DivideButton;
    private javax.swing.JButton EightButton;
    private javax.swing.JButton EqualButton;
    private javax.swing.JButton EqualsButton;
    private javax.swing.JButton FiveButton;
    private javax.swing.JButton FourButton;
    private javax.swing.JButton GTButton;
    private javax.swing.JButton GTEQButton;
    private javax.swing.JButton LTButton;
    private javax.swing.JButton LTEQButton;
    private javax.swing.JButton ModulusButton;
    private javax.swing.JButton MultiplicationButton;
    private javax.swing.JButton NineButton;
    private javax.swing.JButton NotButton;
    private javax.swing.JButton NotEqualButton;
    private javax.swing.JButton ORButton;
    private javax.swing.JButton OneButton;
    private javax.swing.JButton Parenthesis;
    private javax.swing.JButton SevenButton;
    private javax.swing.JButton SixButton;
    private javax.swing.JLabel Stored;
    private javax.swing.JButton SubtrationButton;
    private javax.swing.JTextField TextInput;
    private javax.swing.JButton ThreeButton;
    private javax.swing.JButton TwoButton;
    private javax.swing.JButton ZeroButton;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
